INSERT INTO producto_padre (nombre,unidad)
    VALUES 
	('producto','unidad'),
('aceite vegetal','litro'),
('aji','kilo'),
('aji amarillo','kilo'),
('aji escabeche','kilo'),
('aji limo','kilo'),
('aji mirasol','kilo'),
('ajinomoto','kilo'),
('aji panca','kilo'),
('ajos','kilo'),
('apio','kilo'),
('arroz','kilo'),
('camote','kilo'),
('carne','kilo'),
('cebolla','kilo'),
('cebolla cabeza','kilo'),
('cerveza','litro'),
('chicha de jora','litro'),
('chinchu','atado'),
('choclo','unidad'),
('cordero','kilo'),
('culantro','kilo'),
('espinaca','kilo'),
('fideos','kilo'),
('galleta','unidad'),
('gas','galon'),
('gaseosa cocacola','litro'),
('habas','kilo'),
('hot dog','unidad'),
('huacatay','atado'),
('huevo','unidad'),
('humita','unidad'),
('kion','kilo'),
('leche','litro'),
('lechuga','unidad'),
('limon','kilo'),
('papa amarilla','kilo'),
('papa blanca','kilo'),
('papa guairo','kilo'),
('pasas','gramos'),
('pavita','kilo'),
('pecanas o mani','gramos'),
('peregil','atado'),
('platano','unidad'),
('pollo','presas'),
('pomarola','kilo'),
('poro','kilo'),
('rocoto','kilo'),
('sal','kilo'),
('sillao','litro'),
('tomate','kilo'),
('trigo partido','kilo'),
('trucha','unidad'),
('vinagre','litro'),
('vino','litro'),
('zanahoria','kilo'),
('zapallo','kilo')