# Generated by Django 3.0.1 on 2019-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': True,
            },
        ),
    ]
