# Generated by Django 3.0.1 on 2020-02-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platopadre',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='productopadre',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
