# Generated by Django 3.0.1 on 2020-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoHijoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plato_hijo_venta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PlatoVenta',
        ),
    ]
