# Generated by Django 3.0.2 on 2020-01-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platohijoventa',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
