# Generated by Django 3.0.1 on 2020-01-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platoventa',
            options={'managed': True},
        ),
    ]
