# Generated by Django 3.0.1 on 2020-01-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoHijoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plato_hijo_venta',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PlatoVenta',
        ),
        migrations.AlterModelOptions(
            name='boletacompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='boletaventarestaurante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='platopadre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productohijocompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productohijoventa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productopadre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productoplato',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventabodega',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='platohijoventa',
            name='id_boleta_venta_restaurante',
            field=models.ForeignKey(blank=True, db_column='id_boleta_venta_restaurante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.BoletaVentaRestaurante'),
        ),
        migrations.AddField(
            model_name='platohijoventa',
            name='id_plato_padre',
            field=models.ForeignKey(blank=True, db_column='id_plato_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.PlatoPadre'),
        ),
    ]
