# Generated by Django 3.0.1 on 2020-01-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0002_auto_20200126_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletacompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='boletaventarestaurante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='platohijoventa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='platopadre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productohijocompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productohijoventa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productopadre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productoplato',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventabodega',
            options={'managed': True},
        ),
    ]
