# Generated by Django 3.0.1 on 2020-02-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0002_auto_20200202_2230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoplato',
            unique_together={('producto_padre', 'plato_padre')},
        ),
    ]
