# Generated by Django 3.0.1 on 2019-12-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0003_auto_20191230_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='dni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
