# Generated by Django 3.0.1 on 2020-01-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0003_auto_20200126_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='platohijoventa',
            name='id_boleta_venta_restaurante',
            field=models.ForeignKey(blank=True, db_column='id_boleta_venta_restaurante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.BoletaVentaRestaurante'),
        ),
        migrations.AddField(
            model_name='platohijoventa',
            name='id_plato_padre',
            field=models.ForeignKey(blank=True, db_column='id_plato_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.PlatoPadre'),
        ),
        migrations.AddField(
            model_name='productohijocompra',
            name='id_boleta_compra',
            field=models.ForeignKey(blank=True, db_column='id_boleta_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.BoletaCompra'),
        ),
        migrations.AddField(
            model_name='productohijocompra',
            name='id_producto_padre',
            field=models.ForeignKey(blank=True, db_column='id_producto_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.ProductoPadre'),
        ),
        migrations.AddField(
            model_name='productohijocompra',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.Proveedor'),
        ),
        migrations.AddField(
            model_name='productohijoventa',
            name='id_producto_padre',
            field=models.ForeignKey(blank=True, db_column='id_producto_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.ProductoPadre'),
        ),
        migrations.AddField(
            model_name='productohijoventa',
            name='id_venta_bodega',
            field=models.ForeignKey(blank=True, db_column='id_venta_bodega', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.VentaBodega'),
        ),
        migrations.AddField(
            model_name='productoplato',
            name='id_plato_padre',
            field=models.ForeignKey(blank=True, db_column='id_plato_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.PlatoPadre'),
        ),
        migrations.AddField(
            model_name='productoplato',
            name='id_producto_padre',
            field=models.ForeignKey(blank=True, db_column='id_producto_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eica.ProductoPadre'),
        ),
    ]
