# Generated by Django 3.0.1 on 2019-12-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0004_auto_20191230_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': True, 'verbose_name_plural': 'personas'},
        ),
        migrations.AddField(
            model_name='personas',
            name='fecha_creado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
