# Generated by Django 3.0.1 on 2020-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0004_auto_20200129_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletacompra',
            name='responsable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
