# Generated by Django 3.0.1 on 2020-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0005_boletacompra_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletacompra',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
