# Generated by Django 3.0.1 on 2019-12-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0008_auto_20191231_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_creado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
