# Generated by Django 3.0.1 on 2019-12-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0009_auto_20191230_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
