# Generated by Django 3.0.1 on 2020-01-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0009_boletaventarestaurante_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platohijoventa',
            old_name='id_plato_padre',
            new_name='plato_padre',
        ),
    ]
