# Generated by Django 3.0.1 on 2020-01-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0010_auto_20200130_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletacompra',
            old_name='id_proveedor',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='platohijoventa',
            old_name='id_boleta_venta_restaurante',
            new_name='boleta_venta_restaurante',
        ),
        migrations.RenameField(
            model_name='productohijocompra',
            old_name='id_boleta_compra',
            new_name='boleta_compra',
        ),
        migrations.RenameField(
            model_name='productohijocompra',
            old_name='id_producto_padre',
            new_name='producto_padre',
        ),
        migrations.RenameField(
            model_name='productohijoventa',
            old_name='id_producto_padre',
            new_name='producto_padre',
        ),
        migrations.RenameField(
            model_name='productohijoventa',
            old_name='id_venta_bodega',
            new_name='venta_bodega',
        ),
        migrations.RenameField(
            model_name='productoplato',
            old_name='id_plato_padre',
            new_name='plato_padre',
        ),
        migrations.RenameField(
            model_name='productoplato',
            old_name='id_producto_padre',
            new_name='producto_padre',
        ),
    ]
