# Generated by Django 3.0.1 on 2019-12-31 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eica', '0010_delete_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni_cliente', models.IntegerField(blank=True, null=True)),
                ('comentarios_cliente', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios_compras', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlFlujoCaja',
            fields=[
                ('id_control_flujo_caja', models.AutoField(primary_key=True, serialize=False)),
                ('monto_ajuste_caja', models.FloatField(blank=True, null=True)),
                ('fecha_apertura_caja', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_caja', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificado_caja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'control_flujo_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=500)),
                ('precio_venta_plato', models.FloatField()),
                ('precio_compra_plato', models.FloatField()),
                ('tipo_plato', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=500)),
                ('descripcion_producto_cp', models.CharField(max_length=500)),
                ('cantidad_envases_producto', models.FloatField()),
                ('cantidad_por_envase_producto', models.FloatField()),
                ('unidad_producto', models.CharField(max_length=100)),
                ('precio_producto', models.FloatField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clave_proveedores', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_transacciones', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_flujo_transaccion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_transaccion', models.FloatField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificado', models.DateTimeField(blank=True, null=True)),
                ('estado_transaccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentasBodega',
            fields=[
                ('id_venta_bodega', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('comentarios_venta_bodega', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ventas_bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentasRestaurante',
            fields=[
                ('id_venta_restaurante', models.AutoField(primary_key=True, serialize=False)),
                ('comentarios_venta_restaurante', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ventas_restaurante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaPlatosPorVentas',
            fields=[
                ('id_venta_restaurante_ventas_restaurante', models.OneToOneField(db_column='id_venta_restaurante_ventas_restaurante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eica.VentasRestaurante')),
                ('precio_venta_unitario', models.FloatField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_platos_por_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaProductosPorCompras',
            fields=[
                ('id_compra_compras', models.OneToOneField(db_column='id_compra_compras', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eica.Compras')),
                ('precio_compra_unitario', models.FloatField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_productos_por_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaProductosPorPlatos',
            fields=[
                ('id_producto_productos', models.OneToOneField(db_column='id_producto_productos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eica.Productos')),
                ('cantidad_producto_por_plato', models.FloatField(blank=True, null=True)),
                ('unidad_producto_por_plato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lista_productos_por_platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaProductosPorVenta',
            fields=[
                ('id_producto_productos', models.OneToOneField(db_column='id_producto_productos', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eica.Productos')),
                ('precio_venta_unitario', models.FloatField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_productos_por_venta',
                'managed': False,
            },
        ),
    ]
