# Generated by Django 3.0.1 on 2020-01-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0012_auto_20200107_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productohijocompra',
            options={'managed': True},
        ),
    ]
