# Generated by Django 3.0.1 on 2020-01-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0014_productohijotransaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productohijotransaccion',
            old_name='fecha_transsacion',
            new_name='fecha_transaccion',
        ),
    ]
