# Generated by Django 3.0.1 on 2020-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eica', '0015_auto_20200131_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='productohijocompra',
            name='cantidad_enviada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
